routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/admin/login', 'AdminController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'AdminController@login')->name('admin.login');
Route::post('/admin/logout', 'AdminController@logout')->name('admin.logout');

Route::middleware(['auth', 'is_admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', 'AdminController@index')->name('index');

    Route::get('/users', 'Admin\UserController@students')->name('users.students');
    Route::get('/users/tutor', 'Admin\UserController@tutors')->name('users.tutors');
    Route::get('/users/create/{type?}', 'Admin\UserController@create')->name('users.create');
    Route::post('/users', 'Admin\UserController@store')->name('users.store');
    Route::get('/users/edit/{user}', 'Admin\UserController@edit')->name('users.edit');
    Route::put('/users/{user}', 'Admin\UserController@update')->name('users.update');
    Route::delete('/users/{user}', 'Admin\UserController@destroy')->name('users.destroy');
});

Route::get('/dashboard/{params?}', 'DashboardController@index')->where('params', '(.*)');
Route::get('/reset/{token}/{email}', 'HomeController@index')->name('reset');
Route::get('/{path?}', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use App\Http\Notifications\ResetPassword;
use App\Http\Notifications\VerifyEmail;
use App\Mail\Contact;
use App\Mail\Register;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, Notifiable;

    protected $fillable = [
        'name', 'email', 'password', 'phone', 'birthday', 'student', 'tutor'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public const VALIDATION_EMAIL = [
        'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
    ];

    public const VALIDATION_RULES = [
        'name' => ['required', 'string', 'max:100'],
        'phone' => ['nullable', 'numeric', 'digits_between:10,11'],
        'birthday' => ['nullable', 'date_format:Y-m-d', 'after_or_equal:1920-01-01']
    ];

    public function getAvatarUrlAttribute()
    {
        return $this->avatar ? asset('storage/' . $this->avatar) : asset('images/default-avatar.png');
    }

    public function setPasswordAttribute($value)
    {
        if($value && $value !== '') {
            $this->attributes['password'] = Hash::make($value);
        }
    }

    public function classrooms()
    {
        return $this->hasMany('App\Classroom')->orderBy('created_at', 'DESC');
    }

    public function subjects()
    {
        return $this->hasMany('App\Subject')->orderBy('created_at', 'DESC');
    }

    public function chapters()
    {
        return $this->hasMany('App\Chapter')->orderBy('order', 'ASC');
    }

    public function studentClassrooms()
    {
        return $this->belongsToMany('App\Classroom', 'classroom_user');
    }

    public function sendEmailVerificationNotification()
    {
        $this->notify(new VerifyEmail());
    }

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPassword($token));
    }

    public function isAdmin() {
        return $this->admin;
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Mail\NewAccount;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;

class UserController extends Controller
{
    protected $entity;
    protected $rules;
    protected $folder;
    protected $name;

    public function __construct()
    {
        $this->entity = 'App\User';
        $this->folder = 'users';
        $this->name = 'Utilisateur';
        $this->rules = User::VALIDATION_RULES;
    }

    public function students()
    {
        $entities = $this->entity::where('student', true)->orderBy('created_at', 'DESC')->get();

        return view('admin.' . $this->folder . '.index',
            ['entities' => $entities]
        );
    }

    public function tutors()
    {
        $entities = $this->entity::where('tutor', true)->orderBy('created_at', 'DESC')->get();

        return view('admin.' . $this->folder . '.index',
            ['entities' => $entities]
        );
    }

    public function show($entity)
    {
        return redirect()->route('admin.' . $this->folder . '.index');
    }

    public function create(Request $request)
    {
        return view('admin.' . $this->folder . '.create', ['request' => $request]);
    }

    public function store(Request $request)
    {
        $inputs = $request->all();
        $rules = array_merge($this->rules, User::VALIDATION_EMAIL);
        Validator::make($inputs, $rules)->validate();

        $entity = new $this->entity();
        $inputs['password'] = Str::random(8);

        if($inputs['type'] === 'tutor') {
            $entity->tutor = true;
        } else {
            $entity->student = true;
        }

        $entity->fill($inputs)->save();

        $entity->email_verified_at = Carbon::now();
        $entity->save();

        if($request->file('avatar')) {
            Storage::delete($entity->avatar);

            $path = $request->file('avatar')->store('avatars');
            $entity->avatar = $path;
            $entity->save();
        }

        Mail::to($entity->email)->send(new NewAccount($entity, $inputs['password']));

        if($entity->tutor) {
            return redirect()->route('admin.' . $this->folder . '.tutors')->with('success', $this->name . ' ajouté !');
        }

        return redirect()->route('admin.' . $this->folder . '.students')->with('success', $this->name . ' ajouté !');
    }

    public function edit($entity)
    {
        $entity = $this->entity::where('id', $entity)->first();

        if(!$entity) {
            Session::flash('error', 'L\''. $this->name .' n\'existe pas');
            return redirect()->back();
        }

        return view('admin.' . $this->folder . '.edit',
            ['entity' => $entity]
        );
    }

    public function update(Request $request, $entity)
    {
        $entity = $this->entity::where('id', $entity)->first();

        if (!$entity) {
            Session::flash('error', 'L\''. $this->name .' n\'existe pas');
            return redirect()->back();
        }

        $inputs = $request->all();
        Validator::make($inputs, $this->rules)->validate();

        if($inputs['type'] === 'tutor') {
            $entity->student = false;
            $entity->tutor = true;
        } else {
            $entity->student = true;
            $entity->tutor = false;
        }

        $entity->fill($inputs)->save();

        if($request->file('avatar')) {
            Storage::delete($entity->avatar);

            $path = $request->file('avatar')->store('avatars');
            $entity->avatar = $path;
            $entity->save();
        }

        if($entity->tutor) {
            return redirect()->route('admin.' . $this->folder . '.tutors')->with('success', $this->name . ' supprimé !');
        }

        return redirect()->route('admin.' . $this->folder . '.students')->with('success', $this->name . ' modifié !');
    }

    public function destroy($entity)
    {
        $entity = $this->entity::where('id', $entity)->first();

        if(!$entity) {
            Session::flash('error', 'L\''. $this->name .' n\'existe pas');
            return redirect()->back();
        }

        $tutor = $entity->tutor;

        $entity->delete();

        if($tutor) {
            return redirect()->route('admin.' . $this->folder . '.tutors')->with('success', $this->name . ' supprimé !');
        }

        return redirect()->route('admin.' . $this->folder . '.students')->with('success', $this->name . ' supprimé !');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Chapter;
use App\Classroom;
use App\ClassroomUser;
use App\Http\Requests\StoreUserRequest;
use App\Http\Resources\UserCollection;
use App\Http\Resources\UserResource;
use App\SubChapter;
use App\Subject;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\JsonResponse;

class UserController extends Controller
{
    public function index()
    {
        return new UserCollection(User::all());
    }

    public function show(Request $request)
    {
        return new UserResource($request->user());
    }

    public function update(StoreUserRequest $request, $id)
    {
        $user = User::find($id);
        $user->update($request->all());

        return new UserResource($user);
    }

    public function updateAvatar(Request $request, $id)
    {
        $user = User::find($id);

        if($user->id !== $request->user()->id) {
            return new JsonResponse(['message' => 'Vous ne pouvez pas modifier cet utilisateur'], 422);
        }

        $this->validate($request, [
            'avatar' => 'required|image',
        ]);

        Storage::delete($user->avatar);

        $path = $request->file('avatar')->store('avatars');
        $user->avatar = $path;
        $user->save();

        return new JsonResponse(['data' => $user->avatar_url], 201);
    }

    public function destroy(Request $request, $id)
    {
        $user = User::find($id);

        if($user->id === $request->user()->id) {
            $user->tokens()->where('id', $request->user()->currentAccessToken()->id)->delete();
            $user->delete();
            return new Response('', 201);
        }

        return new JsonResponse(['message' => 'Vous ne pouvez pas supprimer cet utilisateur'], 422);
    }

    public function stats(Request $request, $classroomId = null)
    {
        $user = $request->user();

        if($classroomId) {
            $classroomsId = Classroom::where('id', $classroomId)->where('user_id', $user->id)->pluck('id')->toArray();
        } else {
            $classroomsId = Classroom::where('user_id', $user->id)->pluck('id')->toArray();
        }

        $subjects = Subject::whereIn('classroom_id', $classroomsId)->pluck('id')->toArray();
        $chapters = Chapter::whereIn('subject_id', $subjects)->pluck('id')->toArray();
        $subChapters = SubChapter::whereIn('chapter_id', $chapters)->pluck('id')->toArray();
        $admins = Classroom::where('user_id', $user->id)->whereNotNull('admin_id')->count();
        $classroomUsers = ClassroomUser::whereIn('classroom_id', $classroomsId)->count();

        $array = [
            'nb_classrooms' => count($classroomsId),
            'nb_subjects' => count($subjects),
            'nb_chapters' => count($chapters),
            'nb_sub_chapters' => count($subChapters),
            'nb_admins' => $admins,
            'nb_students' => $classroomUsers,
        ];

        return new JsonResponse(['data' => $array], 201);
    }

    public function lastPosts(Request $request, $classroomId = null)
    {
        $user = $request->user();

        if($classroomId) {
            $classroomsId = Classroom::where('id', $classroomId)->where('user_id', $user->id)->pluck('id')->toArray();
        } else {
            $classroomsId = Classroom::where('user_id', $user->id)->pluck('id')->toArray();
        }

        $subjectsId = Subject::whereIn('classroom_id', $classroomsId)->pluck('id')->toArray();
        $chaptersId = Chapter::whereIn('subject_id', $subjectsId)->pluck('id')->toArray();
        $subChaptersId = SubChapter::whereIn('chapter_id', $chaptersId)->pluck('id')->toArray();

        $subjects = Subject::with('classroom')
            ->whereIn('classroom_id', $classroomsId)
            ->orderBy('created_at', 'DESC')
            ->limit(5)->get();

        $chapters = Chapter::with('subject')->with('subject.classroom')
            ->whereIn('subject_id', $subjectsId)
            ->orderBy('created_at', 'DESC')
            ->limit(5)->get();

        $subChapters = SubChapter::with('chapter')
            ->with('chapter.subject')
            ->with('chapter.subject.classroom')
            ->whereIn('chapter_id', $chaptersId)
            ->orderBy('created_at', 'DESC')
            ->limit(5)->get();

        $data = [];

        foreach ($subjects as $entity) {
            $data[Carbon::parse($entity->created_at)->timestamp] = [
                'id' => $entity->id,
                'name' => $entity->name,
                'type' => 'subject',
                'created_at' => $entity->created_at,
                'classroom' => $entity->classroom->name,
                'classroom_id' => $entity->classroom->id,
                'subject' => $entity->name,
                'subject_id' => $entity->id,
            ];
        }

        foreach ($chapters as $entity) {
            $data[Carbon::parse($entity->created_at)->timestamp] = [
                'id' => $entity->id,
                'name' => $entity->name,
                'type' => 'chapter',
                'created_at' => $entity->created_at,
                'classroom' => $entity->subject->classroom->name,
                'classroom_id' => $entity->subject->classroom->id,
                'subject' => $entity->subject->name,
                'subject_id' => $entity->subject->id,
            ];
        }

        foreach ($subChapters as $entity) {
            $data[Carbon::parse($entity->created_at)->timestamp] = [
                'id' => $entity->id,
                'name' => $entity->name,
                'type' => 'sub-chapter',
                'created_at' => $entity->created_at,
                'classroom' => $entity->chapter->subject->classroom->name,
                'classroom_id' => $entity->chapter->subject->classroom->id,
                'subject' => $entity->chapter->subject->name,
                'subject_id' => $entity->chapter->subject->id,
                'chapter_id' => $entity->chapter->id,
            ];
        }

        ksort($data);
        $data = array_slice($data, -5);

        return new JsonResponse(['data' => $data], 201);
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.app')

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/summernote-bs4.min.css') }}">
@endsection

@section('content')
    <div class="container-fluid">
        <h1 class="mt-4">Utilisateurs</h1>

        <div class="card">
            <div class="card-body">
                <form method="POST" action="{{ route('admin.users.store') }}" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group">
                        <label for="name">Type</label> <br/>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="type" id="tutor" value="tutor"
                                   @if(old('type') && old('type') === 'tutor') checked @endif
                                   @if($request->type && $request->type === 'tutor') checked @endif>
                            <label class="form-check-label" for="tutor">Tuteur</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="type" id="student" value="student"
                                   @if(old('type') && old('type') === 'student') checked @endif
                                   @if($request->type && $request->type === 'student') checked @endif
                            >
                            <label class="form-check-label" for="student">Etudiant</label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="name">Nom</label>
                        <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" id="name" placeholder="name" value="{{ old('name') }}" required>

                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" name="email" class="form-control @error('email') is-invalid @enderror" id="email" value="{{ old('email') }}" placeholder="email" required>

                        @error('email')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="phone">Téléphone</label>
                        <input type="tel" name="phone" class="form-control @error('phone') is-invalid @enderror" id="phone" value="{{ old('phone') }}" placeholder="Téléphone">

                        @error('phone')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="birthday">Année de naissance</label>
                        <input type="date" name="birthday" class="form-control @error('birthday') is-invalid @enderror" id="birthday" value="{{ old('birthday') ?? '1991-01-01' }}" placeholder="Année de naissance">

                        @error('birthday')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="avatar">Avatar</label>
                        <input type="file" class="form-control" id="avatar" name="avatar">
                    </div>

                    <button type="submit" class="btn btn-primary">Créer</button>
                </form>
            </div>
        </div>

    </div>
@endsection

@section('scripts')
    <script src="{{ asset('js/summernote-bs4.min.js') }}"></script>
    <script>
      $(document).ready(function() {
        $('#summernote').summernote({
          height: 400,
          toolbar: [
            ["style", ["style"]],
            ["font", ["bold", "underline", "clear"]],
            ["fontname", ["fontname"]],
            ["color", ["color"]],
            ["para", ["ul", "ol", "paragraph"]],
            ["table", ["table"]],
            ["insert", ["link", "picture"]],
            ["view", ["fullscreen", "codeview", "help"]]
          ],
          defaultFontName: 'Yantramanav',
          fontNames: [
            'Yantramanav', 'Crimson Text', 'Arial', 'Arial Black', 'Times New Roman', 'Verdana',
          ],
          fontNamesIgnoreCheck: ['Yantramanav', 'Crimson Text'],
        });
      });
    </script>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/summernote-bs4.min.css') }}">
@endsection

@section('content')
    <div class="container-fluid">
        <h1 class="mt-4">Utilisateurs</h1>

        <div class="card">
            <div class="card-body">
                <form method="POST" action="{{ route('admin.users.update', ['user' => $entity->id]) }}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')

                    <div class="form-group">
                        <label for="name">Type</label> <br/>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="type" id="tutor" value="tutor"
                                   @if(old('type') && old('type') === 'tutor')
                                    checked
                                   @else
                                    @if($entity->tutor) checked @endif
                                   @endif>
                            <label class="form-check-label" for="tutor">Tuteur</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="type" id="student" value="student"
                                   @if(old('type') && old('type') === 'student')
                                   checked
                                   @else
                                    @if($entity->student) checked @endif
                                   @endif>
                            <label class="form-check-label" for="student">Etudiant</label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="name">Nom</label>
                        <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" id="name"
                               placeholder="name" value="{{ $entity->name ?? old('name') }}" required>

                        @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" name="email" class="form-control @error('email') is-invalid @enderror"
                               id="email" value="{{ $entity->email ?? old('email') }}" placeholder="email" required>

                        @error('email')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="phone">Téléphone</label>
                        <input type="tel" name="phone" class="form-control @error('phone') is-invalid @enderror"
                               id="phone" value="{{ $entity->phone ?? old('phone') }}" placeholder="Téléphone">

                        @error('phone')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="birthday">Année de naissance</label>
                        <input type="date" name="birthday" class="form-control @error('birthday') is-invalid @enderror"
                               id="birthday" value="{{ $entity->birthday ?? old('birthday') }}"
                               placeholder="Année de naissance">

                        @error('birthday')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <div class="form-group">
                        <label for="avatar">Avatar</label>
                        <input type="file" class="form-control" id="avatar" name="avatar">
                    </div>

                    <button type="submit" class="btn btn-primary">Modifier</button>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('js/summernote-bs4.min.js') }}"></script>
    <script>
      $(document).ready(function() {
        $('#summernote').summernote({
          height: 400,
          toolbar: [
            ["style", ["style"]],
            ["font", ["bold", "underline", "clear"]],
            ["fontname", ["fontname"]],
            ["color", ["color"]],
            ["para", ["ul", "ol", "paragraph"]],
            ["table", ["table"]],
            ["insert", ["link", "picture"]],
            ["view", ["fullscreen", "codeview", "help"]]
          ],
          defaultFontName: 'Yantramanav',
          fontNames: [
            'Yantramanav', 'Crimson Text', 'Arial', 'Arial Black', 'Times New Roman', 'Verdana',
          ],
          fontNamesIgnoreCheck: ['Yantramanav', 'Crimson Text'],
        });
      });
    </script>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container-fluid">
        <h1 class="mt-4">Utilisateurs</h1>

        <div class="m-4 d-flex flex-row-reverse">
            @if(Route::currentRouteName() === 'admin.users.students')
                <a type="button" class="btn btn-success" href="{{ route('admin.users.create', ['student']) }}">Ajouter</a>
            @else
                <a type="button" class="btn btn-success" href="{{ route('admin.users.create', ['tutor']) }}">Ajouter</a>
            @endif
        </div>

        <table id="data-table" class="table table-sm">
            <thead>
            <tr>
                <th scope="col">Avatar</th>
                <th scope="col">Nom</th>
                <th scope="col">Email</th>
                <th scope="col">Téléphone</th>
                @if(Route::currentRouteName() === 'admin.users.students')
                    <th scope="col">Date de naissance</th>
                @endif
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($entities as $entity)
                <tr>
                    <td style="width: 100px; height: 100px;">
                        @if($entity->avatar_url)
                            <img src="{{ $entity->avatar_url }}"
                                 alt="{{ $entity->name }}"
                                 style="object-fit: cover; width: 100%; height: 100%;">
                        @endif
                    </td>
                    <td>{{ $entity->name }}</td>
                    <td>{{ $entity->email }}</td>
                    <td>{{ $entity->phone }}</td>
                    @if(Route::currentRouteName() === 'admin.users.students')
                        <td>{{ $entity->birthday }}</td>
                    @endif
                    <td class="d-flex">
                        <a type="button" class="btn btn-primary mr-2" href="{{ route('admin.users.edit', ['user' => $entity->id]) }}">Modifier</a>
                        <form action="{{ route('admin.users.destroy', ['user' => $entity->id]) }}" method="POST" onSubmit="return confirm('Etes vous sur ?');">
                            @csrf
                            @method('DELETE')

                            <button type="submit" class="btn btn-danger">Supprimer</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

@section('scripts')
    <script>
      $( document ).ready(function() {
        $('#data-table').DataTable();
      });
    </script>
@endsection